# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglik <- function(param, dat, I1, I2, I3, n) {
    .Call(`_heckman_loglik`, param, dat, I1, I2, I3, n)
}

rcpp_hello_world <- function() {
    .Call(`_heckman_rcpp_hello_world`)
}

